# vivado 2022.2

[main]
BOARD_PART=www.digilentinc.com:pynq-z1:part0:1.0
BOARD_PART_REPO_PATHS=C:/Users/fabio/AppData/Roaming/Xilinx/Vivado/2022.2/xhub/board_store/xilinx_board_store
PART=xc7z020clg400-1

